#  Blur swaync

layerrule = match:namespace swaync-control-center, blur on
layerrule = match:namespace swaync-notification-window, blur on


layerrule = match:namespace swaync-control-center, ignore_alpha 0.5
layerrule = match:namespace swaync-notification-window, ignore_alpha 0.4

# Rofi


layerrule = match:namespace rofi, blur on
layerrule = match:namespace rofi, animation popin 65%



