-- hyprmono — a monochrome colorscheme built from the hypr-theme palette.
--
-- No hues: syntax is told apart by shade, weight and italics, the same way
-- the rest of the rice is. Colours arrive from
-- ~/.config/hypr-theme/current/neovim.lua, so the same code renders the
-- dark and the light theme (and any future one).

local M = {}

local function hl(group, spec)
  vim.api.nvim_set_hl(0, group, spec)
end

function M.load(p)
  vim.cmd.highlight("clear")
  if vim.fn.exists("syntax_on") == 1 then
    vim.cmd.syntax("reset")
  end
  vim.g.colors_name = "hyprmono"
  vim.o.termguicolors = true

  local bg, fg = p.bg0, p.fg
  local none = "NONE"

  -- ---------------------------------------------------------------- editor
  hl("Normal",        { fg = fg, bg = bg })
  hl("NormalNC",      { fg = fg, bg = bg })
  hl("NormalFloat",   { fg = fg, bg = p.bg1 })
  hl("FloatBorder",   { fg = p.bg4, bg = p.bg1 })
  hl("FloatTitle",    { fg = p.bright, bg = p.bg1, bold = true })
  hl("EndOfBuffer",   { fg = p.bg2 })
  hl("NonText",       { fg = p.bg4 })
  hl("Whitespace",    { fg = p.bg3 })
  hl("SpecialKey",    { fg = p.bg4 })
  hl("Conceal",       { fg = p.dim })

  hl("Cursor",        { fg = bg, bg = p.bright })
  hl("lCursor",       { link = "Cursor" })
  hl("CursorIM",      { link = "Cursor" })
  hl("TermCursor",    { link = "Cursor" })
  hl("CursorLine",    { bg = p.bg_line })
  hl("CursorColumn",  { bg = p.bg_line })
  hl("ColorColumn",   { bg = p.bg1 })
  hl("LineNr",        { fg = p.fg_faint })
  hl("LineNrAbove",   { fg = p.fg_faint })
  hl("LineNrBelow",   { fg = p.fg_faint })
  hl("CursorLineNr",  { fg = p.bright, bold = true })
  hl("SignColumn",    { fg = p.dim, bg = none })
  hl("FoldColumn",    { fg = p.dim })
  hl("Folded",        { fg = p.mid, bg = p.bg1, italic = true })

  hl("Visual",        { bg = p.bg_visual })
  hl("VisualNOS",     { bg = p.bg_visual })
  hl("Search",        { fg = bg, bg = p.mid })
  hl("IncSearch",     { fg = bg, bg = p.bright })
  hl("CurSearch",     { link = "IncSearch" })
  hl("Substitute",    { link = "IncSearch" })
  hl("MatchParen",    { fg = p.bright, bg = p.bg4, bold = true })

  hl("StatusLine",    { fg = fg, bg = p.bg1 })
  hl("StatusLineNC",  { fg = p.dim, bg = p.bg1 })
  hl("WinSeparator",  { fg = p.bg3 })
  hl("VertSplit",     { link = "WinSeparator" })
  hl("TabLine",       { fg = p.mid, bg = p.bg1 })
  hl("TabLineFill",   { bg = p.bg1 })
  hl("TabLineSel",    { fg = p.bright, bg = bg, bold = true })
  hl("WinBar",        { fg = p.mid, bold = true })
  hl("WinBarNC",      { fg = p.dim })

  hl("Pmenu",         { fg = fg, bg = p.bg1 })
  hl("PmenuSel",      { fg = p.bright, bg = p.bg3, bold = true })
  hl("PmenuKind",     { fg = p.mid, bg = p.bg1 })
  hl("PmenuKindSel",  { fg = p.bright, bg = p.bg3 })
  hl("PmenuExtra",    { fg = p.dim, bg = p.bg1 })
  hl("PmenuExtraSel", { fg = p.light, bg = p.bg3 })
  hl("PmenuSbar",     { bg = p.bg2 })
  hl("PmenuThumb",    { bg = p.bg4 })
  hl("WildMenu",      { link = "PmenuSel" })

  hl("Title",         { fg = p.bright, bold = true })
  hl("Directory",     { fg = p.light, bold = true })
  hl("Question",      { fg = p.light })
  hl("MoreMsg",       { fg = p.light })
  hl("ModeMsg",       { fg = p.mid, bold = true })
  hl("MsgArea",       { fg = fg })
  hl("ErrorMsg",      { fg = p.bright, bold = true, underline = true })
  hl("WarningMsg",    { fg = p.light, bold = true })
  hl("QuickFixLine",  { bg = p.bg_visual, bold = true })
  hl("SpellBad",      { sp = p.mid, undercurl = true })
  hl("SpellCap",      { sp = p.dim, undercurl = true })
  hl("SpellLocal",    { sp = p.dim, undercurl = true })
  hl("SpellRare",     { sp = p.dim, undercurl = true })

  -- ---------------------------------------------------------------- syntax
  -- Hierarchy of emphasis, dark and light alike:
  --   bright+bold  keywords, headings, the thing you jump to
  --   light        functions, types (italic)
  --   fg           identifiers, plain code
  --   string       strings (a step softer than code)
  --   mid          numbers, constants, operators
  --   comment      comments (italic, well behind everything)
  hl("Comment",       { fg = p.comment, italic = true })
  hl("Constant",      { fg = p.mid })
  hl("String",        { fg = p.string })
  hl("Character",     { fg = p.string })
  hl("Number",        { fg = p.mid })
  hl("Boolean",       { fg = p.mid, bold = true })
  hl("Float",         { fg = p.mid })
  hl("Identifier",    { fg = fg })
  hl("Function",      { fg = p.light })
  hl("Statement",     { fg = p.bright, bold = true })
  hl("Conditional",   { fg = p.bright, bold = true })
  hl("Repeat",        { fg = p.bright, bold = true })
  hl("Label",         { fg = p.light })
  hl("Operator",      { fg = p.mid })
  hl("Keyword",       { fg = p.bright, bold = true })
  hl("Exception",     { fg = p.bright, bold = true })
  hl("PreProc",       { fg = p.light })
  hl("Include",       { fg = p.light, bold = true })
  hl("Define",        { fg = p.light })
  hl("Macro",         { fg = p.light })
  hl("PreCondit",     { fg = p.light })
  hl("Type",          { fg = p.light, italic = true })
  hl("StorageClass",  { fg = p.light, italic = true })
  hl("Structure",     { fg = p.light, italic = true })
  hl("Typedef",       { fg = p.light, italic = true })
  hl("Special",       { fg = p.fg_soft })
  hl("SpecialChar",   { fg = p.mid, bold = true })
  hl("Tag",           { fg = p.light })
  hl("Delimiter",     { fg = p.mid })
  hl("SpecialComment",{ fg = p.mid, italic = true })
  hl("Debug",         { fg = p.mid })
  hl("Underlined",    { underline = true })
  hl("Ignore",        { fg = p.dim })
  hl("Error",         { fg = p.bright, bold = true, underline = true })
  hl("Todo",          { fg = bg, bg = p.light, bold = true })
  hl("Added",         { fg = p.light })
  hl("Changed",       { fg = p.mid })
  hl("Removed",       { fg = p.dim, strikethrough = true })

  -- ------------------------------------------------------------ treesitter
  hl("@variable",               { fg = fg })
  hl("@variable.builtin",       { fg = p.fg_soft, italic = true })
  hl("@variable.parameter",     { fg = p.fg_soft })
  hl("@variable.member",        { fg = fg })
  hl("@constant",               { fg = p.mid })
  hl("@constant.builtin",       { fg = p.mid, bold = true })
  hl("@constant.macro",         { fg = p.light })
  hl("@module",                 { fg = p.light })
  hl("@label",                  { fg = p.light })
  hl("@string",                 { link = "String" })
  hl("@string.escape",          { fg = p.mid, bold = true })
  hl("@string.regexp",          { fg = p.mid })
  hl("@string.special.url",     { fg = p.mid, underline = true })
  hl("@character",              { link = "Character" })
  hl("@number",                 { link = "Number" })
  hl("@boolean",                { link = "Boolean" })
  hl("@type",                   { link = "Type" })
  hl("@type.builtin",           { fg = p.fg_soft, italic = true })
  hl("@attribute",              { fg = p.mid, italic = true })
  hl("@property",               { fg = fg })
  hl("@function",               { link = "Function" })
  hl("@function.builtin",       { fg = p.light, italic = true })
  hl("@function.call",          { fg = p.light })
  hl("@function.macro",         { fg = p.light })
  hl("@function.method",        { fg = p.light })
  hl("@constructor",            { fg = p.light, italic = true })
  hl("@operator",               { link = "Operator" })
  hl("@keyword",                { link = "Keyword" })
  hl("@keyword.function",       { fg = p.bright, bold = true })
  hl("@keyword.operator",       { fg = p.mid, bold = true })
  hl("@keyword.return",         { fg = p.bright, bold = true })
  hl("@keyword.import",         { link = "Include" })
  hl("@keyword.conditional",    { link = "Conditional" })
  hl("@keyword.repeat",         { link = "Repeat" })
  hl("@keyword.exception",      { link = "Exception" })
  hl("@punctuation.delimiter",  { fg = p.mid })
  hl("@punctuation.bracket",    { fg = p.fg_soft })
  hl("@punctuation.special",    { fg = p.mid })
  hl("@comment",                { link = "Comment" })
  hl("@comment.todo",           { link = "Todo" })
  hl("@comment.note",           { fg = bg, bg = p.mid, bold = true })
  hl("@comment.warning",        { fg = bg, bg = p.light, bold = true })
  hl("@comment.error",          { fg = bg, bg = p.bright, bold = true })
  hl("@tag",                    { fg = p.light })
  hl("@tag.attribute",          { fg = p.fg_soft, italic = true })
  hl("@tag.delimiter",          { fg = p.mid })
  hl("@markup.heading",         { fg = p.bright, bold = true })
  hl("@markup.strong",          { bold = true })
  hl("@markup.italic",          { italic = true })
  hl("@markup.strikethrough",   { strikethrough = true })
  hl("@markup.underline",       { underline = true })
  hl("@markup.link",            { fg = p.light, underline = true })
  hl("@markup.link.url",        { fg = p.mid, underline = true })
  hl("@markup.raw",             { fg = p.string })
  hl("@markup.list",            { fg = p.mid })
  hl("@markup.list.checked",    { fg = p.dim })
  hl("@diff.plus",              { link = "Added" })
  hl("@diff.minus",             { link = "Removed" })
  hl("@diff.delta",             { link = "Changed" })

  -- semantic tokens follow treesitter
  hl("@lsp.type.class",         { link = "@type" })
  hl("@lsp.type.function",      { link = "@function" })
  hl("@lsp.type.method",        { link = "@function.method" })
  hl("@lsp.type.parameter",     { link = "@variable.parameter" })
  hl("@lsp.type.property",      { link = "@property" })
  hl("@lsp.type.variable",      { link = "@variable" })
  hl("@lsp.type.keyword",       { link = "@keyword" })
  hl("@lsp.type.comment",       { link = "@comment" })

  -- ------------------------------------------------------------ diagnostics
  -- one hue is no hue: severity is shown by strength + underline style
  hl("DiagnosticError",            { fg = p.bright, bold = true })
  hl("DiagnosticWarn",             { fg = p.light })
  hl("DiagnosticInfo",             { fg = p.mid })
  hl("DiagnosticHint",             { fg = p.dim })
  hl("DiagnosticOk",               { fg = p.mid })
  hl("DiagnosticUnderlineError",   { sp = p.bright, undercurl = true })
  hl("DiagnosticUnderlineWarn",    { sp = p.light, undercurl = true })
  hl("DiagnosticUnderlineInfo",    { sp = p.mid, underdotted = true })
  hl("DiagnosticUnderlineHint",    { sp = p.dim, underdotted = true })
  hl("DiagnosticVirtualTextError", { fg = p.light, bg = p.bg1, bold = true })
  hl("DiagnosticVirtualTextWarn",  { fg = p.mid, bg = p.bg1 })
  hl("DiagnosticVirtualTextInfo",  { fg = p.dim, bg = p.bg1 })
  hl("DiagnosticVirtualTextHint",  { fg = p.dim, bg = p.bg1 })
  hl("DiagnosticUnnecessary",      { fg = p.dim })
  hl("DiagnosticDeprecated",       { sp = p.dim, strikethrough = true })
  hl("LspReferenceText",           { bg = p.bg2 })
  hl("LspReferenceRead",           { bg = p.bg2 })
  hl("LspReferenceWrite",          { bg = p.bg3 })
  hl("LspInlayHint",               { fg = p.dim, bg = p.bg_soft, italic = true })
  hl("LspCodeLens",                { fg = p.dim, italic = true })
  hl("LspSignatureActiveParameter",{ fg = p.bright, bold = true })

  -- ------------------------------------------------------------------ diff
  hl("DiffAdd",       { bg = p.bg2 })
  hl("DiffChange",    { bg = p.bg1 })
  hl("DiffDelete",    { fg = p.dim, bg = p.bg1 })
  hl("DiffText",      { bg = p.bg3, bold = true })
  hl("diffAdded",     { link = "Added" })
  hl("diffRemoved",   { link = "Removed" })
  hl("diffChanged",   { link = "Changed" })

  -- --------------------------------------------------------------- plugins
  -- gitsigns: real hues, like the file tree in VS Code
  local g = p.git or { added = p.light, modified = p.mid, deleted = p.dim }
  hl("GitSignsAdd",         { fg = g.added })
  hl("GitSignsChange",      { fg = g.modified })
  hl("GitSignsDelete",      { fg = g.deleted })
  hl("GitSignsAddNr",       { fg = g.added })
  hl("GitSignsChangeNr",    { fg = g.modified })
  hl("GitSignsDeleteNr",    { fg = g.deleted })
  hl("GitSignsAddInline",   { bg = p.bg2 })
  hl("GitSignsChangeInline",{ bg = p.bg2 })
  hl("GitSignsDeleteInline",{ bg = p.bg2 })
  hl("NeoTreeGitAdded",     { fg = g.added })
  hl("NeoTreeGitDeleted",   { fg = g.deleted })
  hl("NeoTreeGitConflict",  { fg = g.conflict or g.modified })
  hl("SnacksPickerGitStatusAdded",     { fg = g.added })
  hl("SnacksPickerGitStatusModified",  { fg = g.modified })
  hl("SnacksPickerGitStatusDeleted",   { fg = g.deleted })
  hl("SnacksPickerGitStatusUntracked", { fg = g.added })
  hl("GitSignsCurrentLineBlame", { fg = p.comment, italic = true })
  -- telescope / snacks picker
  hl("TelescopeNormal",         { fg = fg, bg = p.bg1 })
  hl("TelescopeBorder",         { fg = p.bg4, bg = p.bg1 })
  hl("TelescopeTitle",          { fg = p.bright, bold = true })
  hl("TelescopeSelection",      { fg = p.bright, bg = p.bg3, bold = true })
  hl("TelescopeSelectionCaret", { fg = p.bright, bg = p.bg3 })
  hl("TelescopeMatching",       { fg = p.bright, bold = true, underline = true })
  hl("TelescopePromptPrefix",   { fg = p.light })
  hl("SnacksPickerMatch",       { fg = p.bright, bold = true, underline = true })
  hl("SnacksPickerDir",         { fg = p.dim })
  hl("SnacksPickerPathHidden",  { fg = p.dim })
  hl("SnacksIndent",            { fg = p.bg3 })
  hl("SnacksIndentScope",       { fg = p.bg4 })
  hl("SnacksDashboardHeader",   { fg = p.light })
  hl("SnacksDashboardIcon",     { fg = p.mid })
  hl("SnacksDashboardKey",      { fg = p.bright, bold = true })
  hl("SnacksDashboardDesc",     { fg = fg })
  hl("SnacksDashboardFooter",   { fg = p.dim, italic = true })
  hl("SnacksNotifierInfo",      { fg = fg, bg = p.bg1 })
  hl("SnacksNotifierWarn",      { fg = p.light, bg = p.bg1 })
  hl("SnacksNotifierError",     { fg = p.bright, bg = p.bg1 })
  hl("SnacksNotifierBorderInfo", { fg = p.bg4, bg = p.bg1 })
  hl("SnacksNotifierBorderWarn", { fg = p.mid, bg = p.bg1 })
  hl("SnacksNotifierBorderError",{ fg = p.light, bg = p.bg1 })
  -- which-key
  hl("WhichKey",           { fg = p.bright, bold = true })
  hl("WhichKeyGroup",      { fg = p.light })
  hl("WhichKeyDesc",       { fg = fg })
  hl("WhichKeySeparator",  { fg = p.dim })
  hl("WhichKeyNormal",     { fg = fg, bg = p.bg1 })
  hl("WhichKeyBorder",     { fg = p.bg4, bg = p.bg1 })
  -- noice / cmdline / notify
  hl("NoiceCmdlinePopupBorder", { fg = p.bg4 })
  hl("NoiceCmdlineIcon",        { fg = p.light })
  hl("NotifyINFOBorder",   { fg = p.bg4 })
  hl("NotifyINFOTitle",    { fg = p.light })
  hl("NotifyINFOIcon",     { fg = p.light })
  hl("NotifyWARNBorder",   { fg = p.mid })
  hl("NotifyWARNTitle",    { fg = p.light })
  hl("NotifyWARNIcon",     { fg = p.light })
  hl("NotifyERRORBorder",  { fg = p.light })
  hl("NotifyERRORTitle",   { fg = p.bright })
  hl("NotifyERRORIcon",    { fg = p.bright })
  -- bufferline
  hl("BufferLineFill",              { bg = p.bg1 })
  hl("BufferLineBackground",        { fg = p.dim, bg = p.bg1 })
  hl("BufferLineBufferSelected",    { fg = p.bright, bg = bg, bold = true })
  hl("BufferLineBufferVisible",     { fg = p.mid, bg = p.bg1 })
  hl("BufferLineIndicatorSelected", { fg = p.bright, bg = bg })
  hl("BufferLineSeparator",         { fg = p.bg1, bg = p.bg1 })
  hl("BufferLineSeparatorSelected", { fg = p.bg1, bg = bg })
  hl("BufferLineModified",          { fg = p.mid, bg = p.bg1 })
  hl("BufferLineModifiedSelected",  { fg = p.light, bg = bg })
  -- lazy / mason
  hl("LazyH1",           { fg = bg, bg = p.light, bold = true })
  hl("LazyH2",           { fg = p.bright, bold = true })
  hl("LazyButton",       { fg = fg, bg = p.bg2 })
  hl("LazyButtonActive", { fg = bg, bg = p.light, bold = true })
  hl("LazySpecial",      { fg = p.light })
  hl("LazyReasonPlugin", { fg = p.mid })
  hl("LazyProgressDone", { fg = p.light })
  hl("LazyProgressTodo", { fg = p.bg4 })
  hl("MasonHeader",      { fg = bg, bg = p.light, bold = true })
  hl("MasonHighlight",   { fg = p.light })
  hl("MasonHighlightBlockBold", { fg = bg, bg = p.light, bold = true })
  hl("MasonMutedBlock",  { fg = p.mid, bg = p.bg2 })
  -- flash / mini
  hl("FlashLabel",       { fg = bg, bg = p.bright, bold = true })
  hl("FlashMatch",       { fg = p.bright, underline = true })
  hl("FlashCurrent",     { fg = p.bright, bold = true, underline = true })
  hl("FlashBackdrop",    { fg = p.dim })
  hl("MiniIconsGrey",    { fg = p.mid })
  hl("MiniIconsAzure",   { fg = p.light })
  hl("MiniIconsBlue",    { fg = p.light })
  hl("MiniIconsCyan",    { fg = p.mid })
  hl("MiniIconsGreen",   { fg = p.mid })
  hl("MiniIconsOrange",  { fg = p.light })
  hl("MiniIconsPurple",  { fg = p.mid })
  hl("MiniIconsRed",     { fg = p.light })
  hl("MiniIconsYellow",  { fg = p.light })
  -- illuminate / indent
  hl("IlluminatedWordText",  { bg = p.bg2 })
  hl("IlluminatedWordRead",  { bg = p.bg2 })
  hl("IlluminatedWordWrite", { bg = p.bg3 })
  hl("IblIndent",        { fg = p.bg3 })
  hl("IblScope",         { fg = p.bg4 })
  -- neo-tree / trouble / dashboard
  hl("NeoTreeNormal",         { fg = fg, bg = p.bg1 })
  hl("NeoTreeNormalNC",       { fg = fg, bg = p.bg1 })
  hl("NeoTreeDirectoryName",  { fg = p.light })
  hl("NeoTreeDirectoryIcon",  { fg = p.mid })
  hl("NeoTreeRootName",       { fg = p.bright, bold = true })
  hl("NeoTreeGitModified",    { fg = g.modified })
  hl("NeoTreeGitUntracked",   { fg = g.added, italic = true })
  hl("NeoTreeIndentMarker",   { fg = p.bg3 })
  hl("TroubleNormal",         { fg = fg, bg = p.bg1 })
  hl("TroubleText",           { fg = fg })

  -- ------------------------------------------------------ terminal palette
  local t = p.term
  if t then
    for i = 0, 15 do
      vim.g["terminal_color_" .. i] = t[i]
    end
  end
end

return M
