# BACKGROUND
background {
    #monitor =
    path = ~/.config/hypr/hyprlock.png
    blur_passes = 4
    contrast = 0.8916
    brightness = 0.8172
    vibrancy = 0.1696
    vibrancy_darkness = 0.0
}

# GENERAL
general {
    no_fade_in = false
    grace = 0
    disable_loading_bar = true
}

# TIME
label {
    monitor =
     text = cmd[update:1000] echo "$(date +"%-I:%M%p")"
    color = rgba(255, 255, 255, 0.8)
    font_size = 100
    font_family = JetBrains Mono Nerd Font
    position = 0, -90
    halign = center
    valign = top
}

# DAY-DATE-MONTH
# label {
#     monitor =
#     text = cmd[update:1000] echo "<span>$(date '+%A, %d %B')</span>"
#     color = rgba(255, 255, 255, 0.9)
#     font_size = 30
#     font_family = JetBrains Mono Nerd Font
#     position = 0, 420
#     halign = center
#     valign = center
# }

#mm date venole uncomment cheithal mathhi ellam set ahnu


# LOGO
# label {
#     monitor =
#     text =  
#     color = rgba(255, 255, 255, 0.65)
#     font_size = 55
#     position = 0, 60
#     halign = center
#     valign = center
# }

# USER
label {
    monitor =
    text = Hello, $USER
    color = rgba(255, 255, 255, .8)
    font_size = 25
    font_family = JetBrains Mono Nerd Font
    position = 0, 
    halign = center
    valign = center
}

# INPUT FIELD
input-field {
    monitor =
    size = 340, 62
    rounding = 5
    outline_thickness = 2
    dots_size = 0.2 # Scale of input-field height, 0.2 - 0.8
    dots_spacing = 1.0 # Scale of dots' absolute size, 0.0 - 1.0
    dots_center = true
    outer_color = rgba(207, 207, 207, 0.6)
    inner_color = rgba(64, 64, 64, 0.4)
    font_color = rgb(200, 200, 200)
    fade_on_empty = false
    #fade_timeout = 0
    font_family = JetBrains Mono Nerd Font
    placeholder_text = <i><span foreground="##ffffff99"></span></i>
    hide_input = false
    position = 0, -75
    halign = center
    valign = center
}

# CURRENT SONG
label {
    monitor =
    text = cmd[update:1000] echo "$(~/.config/hypr/scripts/songdetail.sh)" 
    color = rgba(200, 200, 200, .75)
    font_size = 16
    font_family = JetBrains Mono Nerd Font
    position = 0, 80
    halign = center
    valign = bottom
}
