# GENERATED by hypr-theme — theme: {{ name }} ({{ mode }}). Do not edit.
# Installed as ~/.config/btop/themes/hypr-theme.theme and selected in btop.conf.
# Hued themes follow the upstream btop layout (one hue per box, real
# green→yellow→red style gradients); monochrome themes run every graph from
# dim through mid to bright greys. main_bg is empty so kitty's translucent
# background shows.

theme[main_bg]=""
theme[main_fg]="{{ fg }}"
theme[title]="{{ hued fg accent_bright }}"
theme[hi_fg]="{{ hued blue accent_bright }}"
theme[selected_bg]="{{ hued bg4 bg3 }}"
theme[selected_fg]="{{ hued blue accent_bright }}"
theme[inactive_fg]="{{ hued grey1 accent_dim }}"
theme[graph_text]="{{ hued accent_light accent_mid }}"
theme[meter_bg]="{{ hued bg4 bg3 }}"
theme[proc_misc]="{{ hued accent_light accent_mid }}"

theme[cpu_box]="{{ hued purple grey1 }}"
theme[mem_box]="{{ hued green grey1 }}"
theme[net_box]="{{ hued red grey1 }}"
theme[proc_box]="{{ hued blue grey1 }}"
theme[div_line]="{{ hued accent_dim grey0 }}"

theme[temp_start]="{{ hued yellow accent_dim }}"
theme[temp_mid]="{{ hued orange accent_mid }}"
theme[temp_end]="{{ hued red accent_bright }}"

theme[cpu_start]="{{ hued aqua accent_dim }}"
theme[cpu_mid]="{{ hued blue accent_mid }}"
theme[cpu_end]="{{ hued accent_bright accent_bright }}"

theme[free_start]="{{ hued purple accent_dim }}"
theme[free_mid]="{{ hued accent_bright accent_mid }}"
theme[free_end]="{{ hued blue accent_light }}"

theme[cached_start]="{{ hued aqua accent_dim }}"
theme[cached_mid]="{{ hued blue accent_mid }}"
theme[cached_end]="{{ hued accent_bright accent_light }}"

theme[available_start]="{{ hued orange accent_dim }}"
theme[available_mid]="{{ hued red accent_mid }}"
theme[available_end]="{{ hued critical accent_light }}"

theme[used_start]="{{ hued green accent_dim }}"
theme[used_mid]="{{ hued aqua accent_mid }}"
theme[used_end]="{{ hued blue accent_bright }}"

theme[download_start]="{{ hued purple accent_dim }}"
theme[download_mid]="{{ hued accent_bright accent_mid }}"
theme[download_end]="{{ hued blue accent_bright }}"

theme[upload_start]="{{ hued yellow accent_dim }}"
theme[upload_mid]="{{ hued orange accent_mid }}"
theme[upload_end]="{{ hued red accent_bright }}"

theme[process_start]="{{ hued aqua accent_dim }}"
theme[process_mid]="{{ hued blue accent_mid }}"
theme[process_end]="{{ hued purple accent_bright }}"
