# GENERATED by hypr-theme — theme: {{ name }} ({{ mode }}). Do not edit.
# Installed as ~/.config/btop/themes/hypr-theme.theme and selected in btop.conf.
# Monochrome: graphs run from dim through mid to bright greys instead of
# green-yellow-red. main_bg is empty so kitty's translucent background shows.

theme[main_bg]=""
theme[main_fg]="{{ fg }}"
theme[title]="{{ accent_bright }}"
theme[hi_fg]="{{ accent_bright }}"
theme[selected_bg]="{{ bg3 }}"
theme[selected_fg]="{{ accent_bright }}"
theme[inactive_fg]="{{ accent_dim }}"
theme[graph_text]="{{ accent_mid }}"
theme[meter_bg]="{{ bg3 }}"
theme[proc_misc]="{{ accent_mid }}"

theme[cpu_box]="{{ grey1 }}"
theme[mem_box]="{{ grey1 }}"
theme[net_box]="{{ grey1 }}"
theme[proc_box]="{{ grey1 }}"
theme[div_line]="{{ grey0 }}"

theme[temp_start]="{{ accent_dim }}"
theme[temp_mid]="{{ accent_mid }}"
theme[temp_end]="{{ accent_bright }}"

theme[cpu_start]="{{ accent_dim }}"
theme[cpu_mid]="{{ accent_mid }}"
theme[cpu_end]="{{ accent_bright }}"

theme[free_start]="{{ accent_dim }}"
theme[free_mid]="{{ accent_mid }}"
theme[free_end]="{{ accent_light }}"

theme[cached_start]="{{ accent_dim }}"
theme[cached_mid]="{{ accent_mid }}"
theme[cached_end]="{{ accent_light }}"

theme[available_start]="{{ accent_dim }}"
theme[available_mid]="{{ accent_mid }}"
theme[available_end]="{{ accent_light }}"

theme[used_start]="{{ accent_dim }}"
theme[used_mid]="{{ accent_mid }}"
theme[used_end]="{{ accent_bright }}"

theme[download_start]="{{ accent_dim }}"
theme[download_mid]="{{ accent_mid }}"
theme[download_end]="{{ accent_bright }}"

theme[upload_start]="{{ accent_dim }}"
theme[upload_mid]="{{ accent_mid }}"
theme[upload_end]="{{ accent_bright }}"

theme[process_start]="{{ accent_dim }}"
theme[process_mid]="{{ accent_mid }}"
theme[process_end]="{{ accent_bright }}"
