// GENERATED by hypr-theme — theme: {{ name }} ({{ mode }}). Do not edit.
// Merged into <profile>/user.js between the hypr-theme markers; Firefox
// applies user.js on every start, so these win over about:config edits.
user_pref("toolkit.legacyUserProfileCustomizations.stylesheets", true);
user_pref("browser.theme.toolbar-theme", {{ dark "0" "1" }});
user_pref("browser.theme.content-theme", {{ dark "0" "1" }});
user_pref("layout.css.prefers-color-scheme.content-override", {{ dark "0" "1" }});
user_pref("browser.theme.dark-private-theme", {{ dark "true" "false" }});
user_pref("ui.systemUsesDarkTheme", {{ dark "1" "0" }});
user_pref("widget.gtk.overlay-scrollbars.enabled", true);
