/* GENERATED by hypr-theme — theme: {{ name }} ({{ mode }}). Do not edit.
 * Installed as <profile>/chrome/userChrome.css for every Firefox profile
 * (needs toolkit.legacyUserProfileCustomizations.stylesheets = true, which
 * firefox-user.js sets). Firefox reads it once at startup — restart to apply.
 *
 * Firefox ≥ 130 styles its chrome from design-system tokens; overriding the
 * tokens on :root recolours toolbars, tabs, urlbar, panels, menus and the
 * sidebar in one go. Layout (4px radius, 1px border) matches the rice. */

:root {
  color-scheme: {{ mode }} !important;

  /* surfaces */
  --background-color-canvas: {{ bg2 }} !important;
  --background-color-box: {{ bg1 }} !important;
  --background-color-list-item-hover: {{ bg3 }} !important;
  --toolbox-background-color: {{ bg0 }} !important;
  --toolbox-background-color-inactive: {{ bg0 }} !important;
  --toolbar-background-color: {{ bg0 }} !important;
  --lwt-accent-color: {{ bg0 }} !important;
  --lwt-accent-color-inactive: {{ bg0 }} !important;
  --tabpanel-background-color: {{ bg2 }} !important;

  /* text */
  --text-color: {{ fg }} !important;
  --toolbox-text-color: {{ fg }} !important;
  --toolbox-text-color-inactive: {{ accent_mid }} !important;
  --toolbar-text-color: {{ fg }} !important;
  --lwt-text-color: {{ fg }} !important;
  --toolbarbutton-icon-fill: {{ accent_light }} !important;
  --toolbarbutton-icon-fill-attention: {{ hued blue accent_bright }} !important;
  --toolbarbutton-icon-fill-attention-text: {{ bg0 }} !important;
  --toolbarseparator-color: {{ bg4 }} !important;

  /* accent, focus, links */
  --color-accent-primary: {{ hued blue accent_bright }} !important;
  --color-accent-primary-hover: {{ hued accent_bright fg }} !important;
  --color-accent-primary-active: {{ hued purple accent_light }} !important;
  --focus-outline-color: {{ accent_bright }} !important;
  --link-color: {{ hued blue accent_bright }} !important;
  --link-color-hover: {{ hued accent_bright fg }} !important;
  --link-color-active: {{ hued purple accent_light }} !important;

  /* borders */
  --border-color: {{ bg3 }} !important;
  --border-color-interactive: {{ bg4 }} !important;
  --border-color-deemphasized: {{ bg3 }} !important;
  --chrome-content-separator-color: {{ bg3 }} !important;
  --tabs-navbar-separator-color: {{ bg3 }} !important;

  /* tabs */
  --tab-background-color-selected: {{ bg2 }} !important;
  --tab-background-color-hover: {{ bg1 }} !important;
  --tab-selected-textcolor: {{ fg }} !important;
  --tab-selected-color-scheme: {{ mode }} !important;
  --tab-border-color-accent: {{ accent_bright }} !important;
  --tab-attention-dot-color: {{ hued blue accent_bright }} !important;
  --tab-loading-fill: {{ accent_bright }} !important;

  /* urlbar + search */
  --toolbar-field-background-color: {{ bg1 }} !important;
  --toolbar-field-background-color-focus: {{ bg2 }} !important;
  --toolbar-field-text-color: {{ fg }} !important;
  --toolbar-field-text-color-focus: {{ fg }} !important;
  --toolbar-field-border-color: {{ bg3 }} !important;
  --toolbar-field-border-color-focus: {{ accent_bright }} !important;
  --urlbar-background-color: {{ bg1 }} !important;
  --urlbar-background-color-focus: {{ bg2 }} !important;
  --urlbar-box-background-color: {{ bg3 }} !important;
  --urlbar-box-background-color-hover: {{ bg4 }} !important;
  --urlbar-box-background-color-active: {{ bg4 }} !important;
  --urlbar-box-background-color-focus: {{ bg3 }} !important;
  --urlbar-box-text-color: {{ accent_light }} !important;
  --urlbar-box-text-color-hover: {{ fg }} !important;
  --urlbarView-result-button-hover-background-color: {{ bg3 }};
  --urlbarView-result-button-hover-color: {{ fg }};
  --urlbarView-result-button-selected-background-color: {{ accent_bright }};
  --urlbarView-result-button-selected-color: {{ bg0 }};

  /* popups, menus, sidebar */
  --panel-background-color: {{ bg1 }} !important;
  --panel-text-color: {{ fg }} !important;
  --panel-border-color: {{ bg3 }} !important;
  --panel-border-radius: 4px !important;
  --arrowpanel-background: {{ bg1 }} !important;
  --arrowpanel-color: {{ fg }} !important;
  --arrowpanel-border-color: {{ bg3 }} !important;
  --sidebar-background-color: {{ bg1 }} !important;
  --sidebar-text-color: {{ fg }} !important;
  --sidebar-border-color: {{ bg3 }} !important;
  --sidebar-launcher-surface-color: {{ bg0 }} !important;

  /* buttons (panels, preferences) */
  --button-background-color: {{ bg3 }} !important;
  --button-background-color-hover: {{ bg4 }} !important;
  --button-background-color-active: {{ grey0 }} !important;
  --button-text-color: {{ fg }} !important;
  --button-border-color: {{ bg4 }} !important;
  --button-background-color-primary: {{ accent_bright }} !important;
  --button-background-color-primary-hover: {{ hued blue accent_light }} !important;
  --button-background-color-primary-active: {{ hued purple accent_mid }} !important;
  --button-text-color-primary: {{ bg0 }} !important;
  --button-border-radius: 4px !important;

  --toolbarbutton-border-radius: 4px !important;
}

/* the selected tab keeps a thin accent line — the rice's 1px border language */
#tabbrowser-tabs .tab-background:is([selected], [multiselected]) {
  outline: 1px solid {{ accent_bright | rgba 0.35 }} !important;
  outline-offset: -1px !important;
}

/* menu highlight = the accent, like the launcher's selected row */
menupopup > menuitem:is([_moz-menuactive], :hover),
menupopup > menu:is([_moz-menuactive], :hover) {
  background-color: {{ accent_bright }} !important;
  color: {{ bg0 }} !important;
}

/* window controls / find bar / notifications follow the toolbar */
#navigator-toolbox, #nav-bar, #PersonalToolbar, .browserContainer > findbar {
  background-color: {{ bg0 }} !important;
  border-color: {{ bg3 }} !important;
}
