/* GENERATED by hypr-theme — theme: {{ name }} ({{ mode }}). Do not edit.
 * Installed as <profile>/chrome/userContent.css. Colours Firefox's own pages
 * (new tab, home, preferences, add-ons, reader mode) — web sites are left
 * alone. Restart Firefox to apply. */

@-moz-document url-prefix("about:") {
  :root {
    color-scheme: {{ mode }} !important;
    --background-color-canvas: {{ bg2 }} !important;
    --background-color-box: {{ bg1 }} !important;
    --background-color-list-item-hover: {{ bg3 }} !important;
    --text-color: {{ fg }} !important;
    --border-color: {{ bg3 }} !important;
    --border-color-interactive: {{ bg4 }} !important;
    --color-accent-primary: {{ hued blue accent_bright }} !important;
    --color-accent-primary-hover: {{ hued accent_bright fg }} !important;
    --color-accent-primary-active: {{ hued purple accent_light }} !important;
    --focus-outline-color: {{ accent_bright }} !important;
    --link-color: {{ hued blue accent_bright }} !important;
    --link-color-hover: {{ hued accent_bright fg }} !important;
    --button-background-color: {{ bg3 }} !important;
    --button-background-color-hover: {{ bg4 }} !important;
    --button-text-color: {{ fg }} !important;
    --button-background-color-primary: {{ accent_bright }} !important;
    --button-text-color-primary: {{ bg0 }} !important;
    --in-content-page-background: {{ bg2 }} !important;
    --in-content-page-color: {{ fg }} !important;
    --in-content-box-background: {{ bg1 }} !important;
    --in-content-box-border-color: {{ bg3 }} !important;
    --in-content-primary-button-background: {{ accent_bright }} !important;
    --in-content-primary-button-text-color: {{ bg0 }} !important;
  }
}

@-moz-document url("about:blank"), url("about:home"), url("about:newtab"), url("about:privatebrowsing") {
  :root, body {
    background-color: {{ bg2 }} !important;
    --newtab-background-color: {{ bg2 }} !important;
    --newtab-background-color-secondary: {{ bg1 }} !important;
    --newtab-text-primary-color: {{ fg }} !important;
    --newtab-text-secondary-color: {{ accent_mid }} !important;
    --newtab-contextual-text-primary-color: {{ fg }} !important;
    --newtab-contextual-text-secondary-color: {{ accent_mid }} !important;
    --newtab-element-hover-color: {{ bg3 }} !important;
    --newtab-element-active-color: {{ bg4 }} !important;
    --newtab-element-secondary-color: {{ bg3 }} !important;
    --newtab-element-secondary-hover-color: {{ bg4 }} !important;
    --newtab-element-secondary-active-color: {{ grey0 }} !important;
    --newtab-primary-element-text-color: {{ bg0 }} !important;
    --newtab-primary-element-active-color: {{ accent_bright }} !important;
    --newtab-card-hairline-color: {{ bg3 }} !important;
    --newtab-button-secondary-color: {{ bg3 }} !important;
    --newtab-wordmark-color: {{ accent_light }} !important;
    --newtab-weather-background-color: {{ bg1 }} !important;
    --newtab-wallpaper-color: {{ bg2 }} !important;
  }
}

/* reader view: "dark"/"light" preset colours replaced by the theme's */
@-moz-document url-prefix("about:reader") {
  body {
    --main-background: {{ bg2 }} !important;
    --main-foreground: {{ fg }} !important;
    --toolbar-bgcolor: {{ bg0 }} !important;
    --toolbar-border: {{ bg3 }} !important;
    --link-foreground: {{ hued blue accent_bright }} !important;
  }
}
