[Settings]
# GENERATED by hypr-theme — theme: {{ name }} ({{ mode }}). Do not edit.
gtk-theme-name={{ gtk_theme }}
gtk-icon-theme-name={{ icon_theme }}
gtk-font-name=Inter 11
gtk-cursor-theme-name={{ cursor_theme }}
gtk-cursor-theme-size=24
gtk-application-prefer-dark-theme={{ dark "1" "0" }}
