-- GENERATED by hypr-theme — theme: {{ name }} ({{ mode }}). Do not edit.
-- Loaded from ~/.config/hypr/modules/decorations.lua via dofile().
hl.config({
	general = {
		col = {
			active_border   = "{{ accent_bright | hypr 0.67 }}",
			inactive_border = "{{ mix bg4 accent_dim 60% | hypr 0.67 }}",
		},
	},
	decoration = {
		shadow = {
			color = "{{ mix bg0 bg1 60% | hypr 0.93 }}",
		},
	},
})
