# GENERATED by hypr-theme — theme: {{ name }} ({{ mode }}). Do not edit.
# Installed to ~/.config/kdeglobals. KDE apps read the inlined [Colors:*].
[General]
ColorScheme=HyprTheme
Name={{ name }}
shadeSortColumn=true
widgetStyle={{ qt_style }}

[KDE]
widgetStyle={{ qt_style }}
LookAndFeelPackage=

[Icons]
Theme={{ icon_theme }}

[UiSettings]
ColorScheme=HyprTheme

[Colors:Window]
BackgroundNormal={{ bg0 | kde }}
BackgroundAlternate={{ bg2 | kde }}
ForegroundNormal={{ fg | kde }}
ForegroundInactive={{ accent_mid | kde }}
ForegroundActive={{ accent_bright | kde }}
ForegroundLink={{ accent_bright | kde }}
ForegroundVisited={{ accent_mid | kde }}
ForegroundNegative={{ critical | kde }}
ForegroundNeutral={{ warning | kde }}
ForegroundPositive={{ warning | kde }}
DecorationFocus={{ accent_light | kde }}
DecorationHover={{ bg4 | kde }}

[Colors:View]
BackgroundNormal={{ bg1 | kde }}
BackgroundAlternate={{ bg2 | kde }}
ForegroundNormal={{ fg | kde }}
ForegroundInactive={{ accent_mid | kde }}
ForegroundActive={{ accent_bright | kde }}
ForegroundLink={{ accent_bright | kde }}
ForegroundVisited={{ accent_mid | kde }}
ForegroundNegative={{ critical | kde }}
ForegroundNeutral={{ warning | kde }}
ForegroundPositive={{ warning | kde }}
DecorationFocus={{ accent_light | kde }}
DecorationHover={{ bg4 | kde }}

[Colors:Button]
BackgroundNormal={{ bg2 | kde }}
BackgroundAlternate={{ bg3 | kde }}
ForegroundNormal={{ fg | kde }}
ForegroundInactive={{ accent_mid | kde }}
ForegroundActive={{ accent_bright | kde }}
ForegroundLink={{ accent_bright | kde }}
ForegroundVisited={{ accent_mid | kde }}
ForegroundNegative={{ critical | kde }}
ForegroundNeutral={{ warning | kde }}
ForegroundPositive={{ warning | kde }}
DecorationFocus={{ accent_light | kde }}
DecorationHover={{ bg4 | kde }}

[Colors:Selection]
BackgroundNormal={{ accent_light | kde }}
BackgroundAlternate={{ accent_light | kde }}
ForegroundNormal={{ bg0 | kde }}
ForegroundInactive={{ accent_dim | kde }}
ForegroundActive={{ bg0 | kde }}
ForegroundLink={{ bg0 | kde }}
ForegroundVisited={{ accent_dim | kde }}
ForegroundNegative={{ bg0 | kde }}
ForegroundNeutral={{ bg0 | kde }}
ForegroundPositive={{ bg0 | kde }}
DecorationFocus={{ accent_bright | kde }}
DecorationHover={{ accent_bright | kde }}

[Colors:Tooltip]
BackgroundNormal={{ bg2 | kde }}
BackgroundAlternate={{ bg3 | kde }}
ForegroundNormal={{ fg | kde }}
ForegroundInactive={{ accent_mid | kde }}
ForegroundActive={{ accent_bright | kde }}
ForegroundLink={{ accent_bright | kde }}
ForegroundVisited={{ accent_mid | kde }}
ForegroundNegative={{ critical | kde }}
ForegroundNeutral={{ warning | kde }}
ForegroundPositive={{ warning | kde }}
DecorationFocus={{ accent_light | kde }}
DecorationHover={{ bg4 | kde }}

[Colors:Complementary]
BackgroundNormal={{ bg0 | kde }}
BackgroundAlternate={{ bg2 | kde }}
ForegroundNormal={{ fg | kde }}
ForegroundInactive={{ accent_mid | kde }}
ForegroundActive={{ accent_bright | kde }}
ForegroundLink={{ accent_bright | kde }}
ForegroundVisited={{ accent_mid | kde }}
ForegroundNegative={{ critical | kde }}
ForegroundNeutral={{ warning | kde }}
ForegroundPositive={{ warning | kde }}
DecorationFocus={{ accent_light | kde }}
DecorationHover={{ bg4 | kde }}

[Colors:Header]
BackgroundNormal={{ bg1 | kde }}
BackgroundAlternate={{ bg2 | kde }}
ForegroundNormal={{ fg | kde }}
ForegroundInactive={{ accent_mid | kde }}
ForegroundActive={{ accent_bright | kde }}
ForegroundLink={{ accent_bright | kde }}
ForegroundVisited={{ accent_mid | kde }}
ForegroundNegative={{ critical | kde }}
ForegroundNeutral={{ warning | kde }}
ForegroundPositive={{ warning | kde }}
DecorationFocus={{ accent_light | kde }}
DecorationHover={{ bg4 | kde }}

[WM]
activeBackground={{ bg1 | kde }}
activeForeground={{ fg | kde }}
inactiveBackground={{ bg0 | kde }}
inactiveForeground={{ accent_mid | kde }}
