# GENERATED by hypr-theme — theme: {{ name }} ({{ mode }}). Do not edit.
# Included from ~/.config/kitty/kitty.conf.
background            {{ background }}
foreground            {{ foreground }}
cursor                {{ cursor }}

selection_background  {{ selection_background }}
selection_foreground  {{ selection_foreground }}

color0                {{ color0 }}
color8                {{ color8 }}
color1                {{ color1 }}
color9                {{ color9 }}
color2                {{ color2 }}
color10               {{ color10 }}
color3                {{ color3 }}
color11               {{ color11 }}
color4                {{ color4 }}
color12               {{ color12 }}
color5                {{ color5 }}
color13               {{ color13 }}
color6                {{ color6 }}
color14               {{ color14 }}
color7                {{ color7 }}
color15               {{ color15 }}
