-- GENERATED by hypr-theme — theme: {{ name }} ({{ mode }}). Do not edit.
-- Read by ~/.config/nvim/lua/config/hypr-theme.lua
return {
  colorscheme = "{{ nvim_colorscheme }}",
  background  = "{{ mode }}",
}
