-- GENERATED by hypr-theme — theme: {{ name }} ({{ mode }}). Do not edit.
-- Read by ~/.config/nvim/lua/config/hypr-theme.lua. colorscheme "hyprmono"
-- is built from this palette by lua/hyprmono/init.lua; any other name is
-- loaded as an installed colorscheme; "aether" feeds `aether` below (the
-- palette in Aether/Omarchy names) to omacom/aether.nvim.
return {
  colorscheme = "{{ nvim_colorscheme }}",
  background  = "{{ mode }}",
  palette = {
    bg0 = "{{ bg0 }}", bg1 = "{{ bg1 }}", bg2 = "{{ bg2 }}", bg3 = "{{ bg3 }}", bg4 = "{{ bg4 }}",
    fg = "{{ fg }}", bright = "{{ accent_bright }}", light = "{{ accent_light }}",
    mid = "{{ accent_mid }}", dim = "{{ accent_dim }}",
    warning = "{{ warning }}", critical = "{{ critical }}",
    grey0 = "{{ grey0 }}", grey1 = "{{ grey1 }}", grey2 = "{{ grey2 }}",
    term_bg = "{{ background }}", term_fg = "{{ foreground }}",
    sel_bg = "{{ selection_background }}", sel_fg = "{{ selection_foreground }}",
    -- editor-only shades derived from the palette
    bg_soft   = "{{ mix bg0 bg1 50% }}",
    bg_line   = "{{ mix bg0 bg2 60% }}",
    bg_visual = "{{ mix bg2 bg4 50% }}",
    fg_soft   = "{{ mix fg accent_mid 35% }}",
    fg_faint  = "{{ mix accent_mid accent_dim 50% }}",
    string    = "{{ mix fg accent_mid 55% }}",
    comment   = "{{ mix accent_dim bg4 25% }}",
    -- git status keeps real hues (see [git] in colors.toml)
    git = { added = "{{ added }}", modified = "{{ modified }}", deleted = "{{ deleted }}",
            renamed = "{{ renamed }}", conflict = "{{ conflict }}" },
    term = { [0] = "{{ color0 }}", "{{ color1 }}", "{{ color2 }}", "{{ color3 }}", "{{ color4 }}",
             "{{ color5 }}", "{{ color6 }}", "{{ color7 }}", "{{ color8 }}", "{{ color9 }}", "{{ color10 }}",
             "{{ color11 }}", "{{ color12 }}", "{{ color13 }}", "{{ color14 }}", "{{ color15 }}" },
  },
  aether = {
    bg = "{{ bg2 }}", dark_bg = "{{ bg1 }}", darker_bg = "{{ bg0 }}", lighter_bg = "{{ bg3 }}",
    selection = "{{ bg4 }}", selection_background = "{{ bg4 }}", selection_foreground = "{{ fg }}",
    fg = "{{ fg }}", foreground = "{{ fg }}", background = "{{ bg2 }}", cursor = "{{ cursor }}",
    light_fg = "{{ accent_light }}", bright_fg = "{{ color15 }}", dark_fg = "{{ accent_mid }}", muted = "{{ accent_dim }}",
    accent = "{{ active }}",
    red = "{{ red }}", orange = "{{ orange }}", yellow = "{{ yellow }}", green = "{{ green }}",
    cyan = "{{ aqua }}", blue = "{{ blue }}", purple = "{{ purple }}", magenta = "{{ purple }}",
    brown = "{{ mix orange bg3 50% }}",
    bright_red = "{{ color9 }}", bright_green = "{{ color10 }}", bright_yellow = "{{ color11 }}",
    bright_blue = "{{ color12 }}", bright_purple = "{{ color13 }}", bright_magenta = "{{ color13 }}",
    bright_cyan = "{{ color14 }}",
  },
}
