/*
 * hypr-dotfiles — shared palette (rofi)             theme: {{ name }} ({{ mode }})
 * GENERATED by hypr-theme — do not edit. Imported by launchers/shared/colors.rasi.
 * rofi surfaces are translucent (Hyprland blurs the layer), so several of
 * these carry an alpha channel.
 */
* {
    background:      {{ dark "#000000" bg0 | rgba 0.74 }};
    background-alt:  {{ mix bg0 bg1 60% | rgba 0.97 }};
    surface:         {{ bg2 | hex8 | upper }};
    surface-alt:     {{ mix bg3 bg4 20% | hex8 | upper }};

    foreground:      {{ accent_bright | hex8 | upper }};
    foreground-alt:  {{ mix accent_light accent_mid 25% | hex8 | upper }};
    muted:           {{ mix accent_mid accent_dim 10% | hex8 | upper }};

    selected:        {{ accent_light | hex8 | upper }};
    active:          {{ accent_bright | hex8 0.8 | upper }};
    urgent:          {{ warning | hex8 | upper }};
    textcolor:       {{ dark "#000000" "#ffffff" | hex8 | upper }};

    /* Borders — accent-light at three strengths */
    border-strong:   {{ accent_light | hex8 0.24 | upper }};
    border-mid:      {{ accent_light | hex8 0.17 | upper }};
    border-faint:    {{ accent_light | hex8 0.08 | upper }};
}
