/*
 * hypr-dotfiles — shared palette (GTK CSS)          theme: {{ name }} ({{ mode }})
 * ============================================================================
 * GENERATED by hypr-theme from themes/<name>/colors.toml — do not edit.
 * Imported by Waybar, SwayNC, wlogout, GTK3, GTK4:
 *
 *     @import '../hypr-theme/current/palette.css';
 */

/* Backgrounds — darkest to lightest */
@define-color bg0 {{ bg0 }};
@define-color bg1 {{ bg1 }};
@define-color bg2 {{ bg2 }};
@define-color bg3 {{ bg3 }};
@define-color bg4 {{ bg4 }};

/* Accents */
@define-color accent-bright {{ accent_bright }};
@define-color accent-light  {{ accent_light }};
@define-color accent-mid    {{ accent_mid }};
@define-color accent-dim    {{ accent_dim }};

/* Semantic */
@define-color active   {{ active }};
@define-color hover    {{ hover }};
@define-color warning  {{ warning }};
@define-color critical {{ critical }};

/* Main foreground */
@define-color fg {{ fg }};

/* Legacy names */
@define-color red    {{ red }};
@define-color orange {{ orange }};
@define-color yellow {{ yellow }};
@define-color green  {{ green }};
@define-color aqua   {{ aqua }};
@define-color blue   {{ blue }};
@define-color purple {{ purple }};

/* Additional greys */
@define-color grey0 {{ grey0 }};
@define-color grey1 {{ grey1 }};
@define-color grey2 {{ grey2 }};
