; GENERATED by hypr-theme — theme: {{ name }} ({{ mode }}). Do not edit.
; Used by both qt5ct and qt6ct via color_scheme_path.
; Each row is 22 #AARRGGBB values in Qt::ColorRole order:
;   0 WindowText  1 Button      2 Light       3 Midlight   4 Dark
;   5 Mid         6 Text        7 BrightText  8 ButtonText 9 Base
;  10 Window     11 Shadow     12 Highlight  13 HighlightedText
;  14 Link       15 LinkVisited 16 AlternateBase 17 NoRole
;  18 ToolTipBase 19 ToolTipText 20 PlaceholderText 21 Accent
[ColorScheme]
active_colors={{ fg | argb }}, {{ bg2 | argb }}, {{ bg4 | argb }}, {{ bg3 | argb }}, {{ bg0 | argb }}, {{ bg1 | argb }}, {{ fg | argb }}, {{ accent_bright | argb }}, {{ fg | argb }}, {{ bg1 | argb }}, {{ bg0 | argb }}, {{ "#000000" | argb 0.1 }}, {{ accent_light | argb }}, {{ bg0 | argb }}, {{ accent_bright | argb }}, {{ accent_mid | argb }}, {{ bg2 | argb }}, {{ "#000000" | argb }}, {{ bg2 | argb 0.95 }}, {{ fg | argb }}, {{ accent_dim | argb }}, {{ accent_bright | argb }}
inactive_colors={{ fg | argb }}, {{ bg2 | argb }}, {{ bg4 | argb }}, {{ bg3 | argb }}, {{ bg0 | argb }}, {{ bg1 | argb }}, {{ fg | argb }}, {{ accent_bright | argb }}, {{ fg | argb }}, {{ bg1 | argb }}, {{ bg0 | argb }}, {{ "#000000" | argb 0.1 }}, {{ accent_mid | argb }}, {{ bg0 | argb }}, {{ accent_bright | argb }}, {{ accent_mid | argb }}, {{ bg2 | argb }}, {{ "#000000" | argb }}, {{ bg2 | argb 0.95 }}, {{ fg | argb }}, {{ accent_dim | argb }}, {{ accent_mid | argb }}
disabled_colors={{ accent_dim | argb }}, {{ bg2 | argb }}, {{ bg4 | argb }}, {{ bg3 | argb }}, {{ bg0 | argb }}, {{ bg1 | argb }}, {{ accent_dim | argb }}, {{ accent_bright | argb }}, {{ accent_dim | argb }}, {{ bg1 | argb }}, {{ bg0 | argb }}, {{ "#000000" | argb 0.1 }}, {{ bg3 | argb }}, {{ accent_dim | argb }}, {{ accent_dim | argb }}, {{ accent_dim | argb }}, {{ bg2 | argb }}, {{ "#000000" | argb }}, {{ bg2 | argb 0.95 }}, {{ accent_dim | argb }}, {{ grey0 | argb }}, {{ accent_dim | argb }}
