/* GENERATED by hypr-theme — theme: {{ name }} ({{ mode }}). Do not edit.
 * Imported by ~/.config/wlogout/style.css. The icon PNGs come in a light
 * ("-rest") and a dark ("-hover") variant; which one sits on which button
 * state flips with the mode, which is why this file is rendered. */
@import '{{ home }}/.config/hypr-theme/current/palette.css';

* {
    box-shadow: none;
    text-shadow: none;
    outline: none;
    transition: background-color 200ms cubic-bezier(0.23, 1, 0.32, 1),
                border-color     200ms cubic-bezier(0.23, 1, 0.32, 1);
}

window {
    background-color: alpha(@bg0, 0.7);
}

button {
    margin: 133px 19px;

    background-color: @bg1;
    border: 1px solid @bg3;
    border-radius: 8px;

    background-repeat: no-repeat;
    background-position: center;
    background-size: 52px 52px;
}

button:focus {
    background-color: @bg2;
    border-color: @accent-dim;
}

button:hover,
button:active {
    background-color: @fg;
    border-color: @fg;
}

/* rest: icon that contrasts with @bg1; hover/active: icon that contrasts with @fg */
#lock            { background-image: url("{{ home }}/.config/wlogout/icons/lock-{{ dark "rest" "hover" }}.png"); }
#logout          { background-image: url("{{ home }}/.config/wlogout/icons/exit-{{ dark "rest" "hover" }}.png"); }
#hibernate       { background-image: url("{{ home }}/.config/wlogout/icons/sleep-{{ dark "rest" "hover" }}.png"); }
#reboot          { background-image: url("{{ home }}/.config/wlogout/icons/reboot-{{ dark "rest" "hover" }}.png"); }
#shutdown        { background-image: url("{{ home }}/.config/wlogout/icons/shutdown-{{ dark "rest" "hover" }}.png"); }

#lock:focus      { background-image: url("{{ home }}/.config/wlogout/icons/lock-{{ dark "focus" "hover" }}.png"); }
#logout:focus    { background-image: url("{{ home }}/.config/wlogout/icons/exit-{{ dark "focus" "hover" }}.png"); }
#hibernate:focus { background-image: url("{{ home }}/.config/wlogout/icons/sleep-{{ dark "focus" "hover" }}.png"); }
#reboot:focus    { background-image: url("{{ home }}/.config/wlogout/icons/reboot-{{ dark "focus" "hover" }}.png"); }
#shutdown:focus  { background-image: url("{{ home }}/.config/wlogout/icons/shutdown-{{ dark "focus" "hover" }}.png"); }

#lock:hover,      #lock:active      { background-image: url("{{ home }}/.config/wlogout/icons/lock-{{ dark "hover" "rest" }}.png"); }
#logout:hover,    #logout:active    { background-image: url("{{ home }}/.config/wlogout/icons/exit-{{ dark "hover" "rest" }}.png"); }
#hibernate:hover, #hibernate:active { background-image: url("{{ home }}/.config/wlogout/icons/sleep-{{ dark "hover" "rest" }}.png"); }
#reboot:hover,    #reboot:active    { background-image: url("{{ home }}/.config/wlogout/icons/reboot-{{ dark "hover" "rest" }}.png"); }
#shutdown:hover,  #shutdown:active  { background-image: url("{{ home }}/.config/wlogout/icons/shutdown-{{ dark "hover" "rest" }}.png"); }
